< option data - countryCode = "DZ"
value = "" > Algeria < /option> <
option data - countryCode = "AD"
value = "" > Andorra < /option> <
option data - countryCode = "AO"
value = "" > Angola < /option> <
option data - countryCode = "AI"
value = "" > Anguilla < /option> <
option data - countryCode = "AG"
value = "" > Antigua & amp;
Barbuda < /option> <
option data - countryCode = "AR"
value = "" > Argentina < /option> <
option data - countryCode = "AM"
value = "" > Armenia < /option> <
option data - countryCode = "AW"
value = "" > Aruba < /option> <
option data - countryCode = "AU"
value = "" > Australia < /option> <
option data - countryCode = "AT"
value = "" > Austria < /option> <
option data - countryCode = "AZ"
value = "" > Azerbaijan < /option> <
option data - countryCode = "BS"
value = "" > Bahamas < /option> <
option data - countryCode = "BH"
value = "" > Bahrain < /option> <
option data - countryCode = "BD"
value = "" > Bangladesh < /option> <
option data - countryCode = "BB"
value = "" > Barbados < /option> <
option data - countryCode = "BY"
value = "" > Belarus < /option> <
option data - countryCode = "BE"
value = "" > Belgium < /option> <
option data - countryCode = "BZ"
value = "" > Belize < /option> <
option data - countryCode = "BJ"
value = "" > Benin < /option> <
option data - countryCode = "BM"
value = "" > Bermuda < /option> <
option data - countryCode = "BT"
value = "" > Bhutan < /option> <
option data - countryCode = "BO"
value = "" > Bolivia < /option> <
option data - countryCode = "BA"
value = "" > Bosnia Herzegovina < /option> <
option data - countryCode = "BW"
value = "" > Botswana < /option> <
option data - countryCode = "BR"
value = "" > Brazil < /option> <
option data - countryCode = "BN"
value = "" > Brunei < /option> <
option data - countryCode = "BG"
value = "" > Bulgaria < /option> <
option data - countryCode = "BF"
value = "" > Burkina Faso < /option> <
option data - countryCode = "BI"
value = "" > Burundi < /option> <
option data - countryCode = "KH"
value = "" > Cambodia < /option> <
option data - countryCode = "CM"
value = "" > Cameroon < /option> <
option data - countryCode = "CA"
value = "" > Canada < /option> <
option data - countryCode = "CV"
value = "" > Cape Verde Islands < /option> <
option data - countryCode = "KY"
value = "" > Cayman Islands < /option> <
option data - countryCode = "CF"
value = "" > Central African Republic < /option> <
option data - countryCode = "CL"
value = "" > Chile < /option> <
option data - countryCode = "CN"
value = "" > China < /option> <
option data - countryCode = "CO"
value = "" > Colombia < /option> <
option data - countryCode = "KM"
value = "" > Comoros < /option> <
option data - countryCode = "CG"
value = "" > Congo < /option> <
option data - countryCode = "CK"
value = "" > Cook Islands < /option> <
option data - countryCode = "CR"
value = "" > Costa Rica < /option> <
option data - countryCode = "HR"
value = "" > Croatia < /option> <
option data - countryCode = "CU"
value = "" > Cuba < /option> <
option data - countryCode = "CY"
value = "" > Cyprus North < /option> <
option data - countryCode = "CY"
value = "" > Cyprus South < /option> <
option data - countryCode = "CZ"
value = "" > Czech Republic < /option> <
option data - countryCode = "DK"
value = "" > Denmark < /option> <
option data - countryCode = "DJ"
value = "" > Djibouti < /option> <
option data - countryCode = "DM"
value = "" > Dominica < /option> <
option data - countryCode = "DO"
value = "" > Dominican Republic < /option> <
option data - countryCode = "EC"
value = "" > Ecuador < /option> <
option data - countryCode = "EG"
value = "" > Egypt < /option> <
option data - countryCode = "SV"
value = "" > El Salvador < /option> <
option data - countryCode = "GQ"
value = "" > Equatorial Guinea < /option> <
option data - countryCode = "ER"
value = "" > Eritrea < /option> <
option data - countryCode = "EE"
value = "" > Estonia < /option> <
option data - countryCode = "ET"
value = "" > Ethiopia < /option> <
option data - countryCode = "FK"
value = "" > Falkland Islands < /option> <
option data - countryCode = "FO"
value = "" > Faroe Islands < /option> <
option data - countryCode = "FJ"
value = "" > Fiji < /option> <
option data - countryCode = "FI"
value = "" > Finland < /option> <
option data - countryCode = "FR"
value = "" > France < /option> <
option data - countryCode = "GF"
value = "" > French Guiana < /option> <
option data - countryCode = "PF"
value = "" > French Polynesia < /option> <
option data - countryCode = "GA"
value = "" > Gabon < /option> <
option data - countryCode = "GM"
value = "" > Gambia < /option> <
option data - countryCode = "GE"
value = "" > Georgia < /option> <
option data - countryCode = "DE"
value = "" > Germany < /option> <
option data - countryCode = "GH"
value = "" > Ghana < /option> <
option data - countryCode = "GI"
value = "" > Gibraltar < /option> <
option data - countryCode = "GR"
value = "" > Greece < /option> <
option data - countryCode = "GL"
value = "" > Greenland < /option> <
option data - countryCode = "GD"
value = "" > Grenada < /option> <
option data - countryCode = "GP"
value = "" > Guadeloupe < /option> <
option data - countryCode = "GU"
value = "" > Guam < /option> <
option data - countryCode = "GT"
value = "" > Guatemala < /option> <
option data - countryCode = "GN"
value = "" > Guinea < /option> <
option data - countryCode = "GW"
value = "" > Guinea - Bissau < /option> <
option data - countryCode = "GY"
value = "" > Guyana < /option> <
option data - countryCode = "HT"
value = "" > Haiti < /option> <
option data - countryCode = "HN"
value = "" > Honduras < /option> <
option data - countryCode = "HK"
value = "" > Hong Kong < /option> <
option data - countryCode = "HU"
value = "" > Hungary < /option> <
option data - countryCode = "IS"
value = "" > Iceland < /option> <
option data - countryCode = "IN"
value = "" > India < /option> <
option data - countryCode = "ID"
value = "" > Indonesia < /option> <
option data - countryCode = "IR"
value = "" > Iran < /option> <
option data - countryCode = "IQ"
value = "" > Iraq < /option> <
option data - countryCode = "IE"
value = "" > Ireland < /option> <
option data - countryCode = "IL"
value = "" > Israel < /option> <
option data - countryCode = "IT"
value = "" > Italy < /option> <
option data - countryCode = "JM"
value = "" > Jamaica < /option> <
option data - countryCode = "JP"
value = "" > Japan < /option> <
option data - countryCode = "JO"
value = "" > Jordan < /option> <
option data - countryCode = "KZ"
value = "" > Kazakhstan < /option> <
option data - countryCode = "KE"
value = "" > Kenya < /option> <
option data - countryCode = "KI"
value = "" > Kiribati < /option> <
option data - countryCode = "KP"
value = "" > Korea North < /option> <
option data - countryCode = "KR"
value = "" > Korea South < /option> <
option data - countryCode = "KW"
value = "" > Kuwait < /option> <
option data - countryCode = "KG"
value = "" > Kyrgyzstan < /option> <
option data - countryCode = "LA"
value = "" > Laos < /option> <
option data - countryCode = "LV"
value = "" > Latvia < /option> <
option data - countryCode = "LB"
value = "" > Lebanon < /option> <
option data - countryCode = "LS"
value = "" > Lesotho < /option> <
option data - countryCode = "LR"
value = "" > Liberia < /option> <
option data - countryCode = "LY"
value = "" > Libya < /option> <
option data - countryCode = "LI"
value = "" > Liechtenstein < /option> <
option data - countryCode = "LT"
value = "" > Lithuania < /option> <
option data - countryCode = "LU"
value = "" > Luxembourg < /option> <
option data - countryCode = "MO"
value = "" > Macao < /option> <
option data - countryCode = "MK"
value = "" > Macedonia < /option> <
option data - countryCode = "MG"
value = "" > Madagascar < /option> <
option data - countryCode = "MW"
value = "" > Malawi < /option> <
option data - countryCode = "MY"
value = "" > Malaysia < /option> <
option data - countryCode = "MV"
value = "" > Maldives < /option> <
option data - countryCode = "ML"
value = "" > Mali < /option> <
option data - countryCode = "MT"
value = "" > Malta < /option> <
option data - countryCode = "MH"
value = "" > Marshall Islands < /option> <
option data - countryCode = "MQ"
value = "" > Martinique < /option> <
option data - countryCode = "MR"
value = "" > Mauritania < /option> <
option data - countryCode = "YT"
value = "" > Mayotte < /option> <
option data - countryCode = "MX"
value = "" > Mexico < /option> <
option data - countryCode = "FM"
value = "" > Micronesia < /option> <
option data - countryCode = "MD"
value = "" > Moldova < /option> <
option data - countryCode = "MC"
value = "" > Monaco < /option> <
option data - countryCode = "MN"
value = "" > Mongolia < /option> <
option data - countryCode = "MS"
value = "" > Montserrat < /option> <
option data - countryCode = "MA"
value = "" > Morocco < /option> <
option data - countryCode = "MZ"
value = "" > Mozambique < /option> <
option data - countryCode = "MN"
value = "" > Myanmar < /option> <
option data - countryCode = "NA"
value = "" > Namibia < /option> <
option data - countryCode = "NR"
value = "" > Nauru < /option> <
option data - countryCode = "NP"
value = "" > Nepal < /option> <
option data - countryCode = "NL"
value = "" > Netherlands < /option> <
option data - countryCode = "NC"
value = "" > New Caledonia < /option> <
option data - countryCode = "NZ"
value = "" > New Zealand < /option> <
option data - countryCode = "NI"
value = "" > Nicaragua < /option> <
option data - countryCode = "NE"
value = "" > Niger < /option> <
option data - countryCode = "NG"
value = "" > Nigeria < /option> <
option data - countryCode = "NU"
value = "" > Niue < /option> <
option data - countryCode = "NF"
value = "" > Norfolk Islands < /option> <
option data - countryCode = "NP"
value = "" > Northern Marianas < /option> <
option data - countryCode = "NO"
value = "" > Norway < /option> <
option data - countryCode = "OM"
value = "" > Oman < /option> <
option data - countryCode = "PW"
value = "" > Palau < /option> <
option data - countryCode = "PA"
value = "" > Panama < /option> <
option data - countryCode = "PG"
value = "" > Papua New Guinea < /option> <
option data - countryCode = "PY"
value = "" > Paraguay < /option> <
option data - countryCode = "PE"
value = "" > Peru < /option> <
option data - countryCode = "PH"
value = "" > Philippines < /option> <
option data - countryCode = "PL"
value = "" > Poland < /option> <
option data - countryCode = "PT"
value = "" > Portugal < /option> <
option data - countryCode = "PR"
value = "" > Puerto Rico < /option> <
option data - countryCode = "QA"
value = "" > Qatar < /option> <
option data - countryCode = "RE"
value = "" > Reunion < /option> <
option data - countryCode = "RO"
value = "" > Romania < /option> <
option data - countryCode = "RU"
value = "" > Russia < /option> <
option data - countryCode = "RW"
value = "" > Rwanda < /option> <
option data - countryCode = "SM"
value = "" > San Marino < /option> <
option data - countryCode = "ST"
value = "" > Sao Tome & amp;
Principe < /option> <
option data - countryCode = "SA"
value = "" > Saudi Arabia < /option> <
option data - countryCode = "SN"
value = "" > Senegal < /option> <
option data - countryCode = "CS"
value = "" > Serbia < /option> <
option data - countryCode = "SC"
value = "" > Seychelles < /option> <
option data - countryCode = "SL"
value = "" > Sierra Leone < /option> <
option data - countryCode = "SG"
value = "" > Singapore < /option> <
option data - countryCode = "SK"
value = "" > Slovak Republic < /option> <
option data - countryCode = "SI"
value = "" > Slovenia < /option> <
option data - countryCode = "SB"
value = "" > Solomon Islands < /option> <
option data - countryCode = "SO"
value = "" > Somalia < /option> <
option data - countryCode = "ZA"
value = "" > South Africa < /option> <
option data - countryCode = "ES"
value = "" > Spain < /option> <
option data - countryCode = "LK"
value = "" > Sri Lanka < /option> <
option data - countryCode = "SH"
value = "" > St.Helena < /option> <
option data - countryCode = "KN"
value = "" > St.Kitts < /option> <
option data - countryCode = "SC"
value = "" > St.Lucia < /option> <
option data - countryCode = "SD"
value = "" > Sudan < /option> <
option data - countryCode = "SR"
value = "" > Suriname < /option> <
option data - countryCode = "SZ"
value = "" > Swaziland < /option> <
option data - countryCode = "SE"
value = "" > Sweden < /option> <
option data - countryCode = "CH"
value = "" > Switzerland < /option> <
option data - countryCode = "SI"
value = "" > Syria < /option> <
option data - countryCode = "TW"
value = "" > Taiwan < /option> <
option data - countryCode = "TJ"
value = "" > Tajikstan < /option> <
option data - countryCode = "TH"
value = "" > Thailand < /option> <
option data - countryCode = "TG"
value = "" > Togo < /option> <
option data - countryCode = "TO"
value = "" > Tonga < /option> <
option data - countryCode = "TT"
value = "" > Trinidad & amp;
Tobago < /option> <
option data - countryCode = "TN"
value = "" > Tunisia < /option> <
option data - countryCode = "TR"
value = "" > Turkey < /option> <
option data - countryCode = "TM"
value = "" > Turkmenistan < /option> <
option data - countryCode = "TM"
value = "" > Turkmenistan < /option> <
option data - countryCode = "TC"
value = "" > Turks & amp;
Caicos Islands < /option> <
option data - countryCode = "TV"
value = "" > Tuvalu < /option> <
option data - countryCode = "UG"
value = "" > Uganda < /option> <
option data - countryCode = "GB"
value = "" > UK < /option> <
option data - countryCode = "UA"
value = "" > Ukraine < /option> <
option data - countryCode = "AE"
value = "" > United Arab Emirates < /option> <
option data - countryCode = "UY"
value = "" > Uruguay < /option> <
option data - countryCode = "US"
value = "" > USA < /option> <
option data - countryCode = "UZ"
value = "" > Uzbekistan < /option> <
option data - countryCode = "VU"
value = "" > Vanuatu < /option> <
option data - countryCode = "VA"
value = "" > Vatican City < /option> <
option data - countryCode = "VE"
value = "" > Venezuela < /option> <
option data - countryCode = "VN"
value = "" > Vietnam < /option> <
option data - countryCode = "VG"
value = "" > Virgin Islands - British < /option> <
option data - countryCode = "VI"
value = "" > Virgin Islands - US < /option> <
option data - countryCode = "WF"
value = "" > Wallis & amp;
Futuna < /option> <
option data - countryCode = "YE"
value = "" > Yemen(North)() < /option> <
option data - countryCode = "YE"
value = "" > Yemen(South)() < /option> <
option data - countryCode = "ZM"
value = "" > Zambia < /option> <
option data - countryCode = "ZW"
value = "" > Zimbabwe < /option>